=head1 NAME

DBIx::Skinny::ModelLoader -

=head1 SYNOPSIS

  package Hoge::DB::Main;
  use DBIx::Skinny;

  package Hoge::Model;
  use DBIx::Skinny::ModelLoader setup => {
      skinny => container('db') # instance
  };

  package Hoge::Page::Hoge;
  use Hoge::Model;

  sub dispatch_hoge {

    #Hoge::Model
    my $model = model;


    #Like $model->insert('user',{id => 1, name => 'hoge'});
    #returns DBIx::Skinny::Row
    my $user = model('User')->create({id => 1,name => 'hoge'});

    #Like $model->search('user',{id => 1});
    #returns DBIx::Skinny::Row
    my $login_user = model('User')->({id => 1});
  }

=head1 DESCRIPTION

DBIx::Skinny::ModelLoader is a Model Loader for DBIx::Skinny

=head1 AUTHOR

Nishibayashi Takuji E<lt>takuji {at} senchan.jpE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

